@startmindmap
* Tělo dokumentu
** Údaje k výjezdu
** Časová osa výjezdu
** Anamnéza
** Urgentní informace
** Nynější onemocnění
** Objektivní nález
** Terapie
** Diagnostický souhrn
** Průběh, Doporučení
** Ukončení
@endmindmap