@startmindmap
* Body
** Dispatch data
** Dispatch timeline
** Patient history
** Urgent information/Alerts
** Present illness
** Objective findings
** Therapy
** Diagnostic summary
** Course of Treatment and Recommendations
** End of care
@endmindmap
