@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logický model |
| <#TECHNOLOGY>  Profil |
endlegend

class "Průběh ošetření" <<LogicalModel>> [[StructureDefinition-LogRecommendationsCz.html]]
note top #EEEEAE [[ConceptMap-ClinicalCourseAndRecommendationsEMS2FHIR-cz.html]]
Concept Mapa
endnote

class "cz-composition-ems" <<Profile>> [[StructureDefinition-cz-composition-ems.html]]
class "cz-procedure-ems" <<Profile>> [[StructureDefinition-cz-procedure-ems.html]]
class "cz-carePlan-ems" <<Profile>> [[StructureDefinition-cz-carePlan-ems.html]]

"Průběh ošetření" <|. "cz-composition-ems"
"Průběh ošetření" <|. "cz-procedure-ems"
"Průběh ošetření" <|. "cz-carePlan-ems"

"cz-composition-ems" -d[hidden]-> "cz-procedure-ems"
"cz-procedure-ems" -d[hidden]-> "cz-carePlan-ems"

@enduml
