@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend

class "Dispatch data" <<LogicalModel>> [[StructureDefinition-DispatchDataCz.html]]
note top #EEEEAE [[ConceptMap-DispatchDataEMS2FHIR-cz.html]]
Concept Map
endnote

class "cz-composition-ems" <<Profile>> [[StructureDefinition-cz-composition-ems.html]]
class "cz-task-ems" <<Profile>> [[StructureDefinition-cz-task-ems.html]]
class "cz-vehicle-location-ems" <<Profile>> [[StructureDefinition-cz-vehicle-location-ems.html]]
class "cz-location-ems" <<Profile>> [[StructureDefinition-cz-location-ems.html]]
class "cz-careteam-ems" <<Profile>> [[StructureDefinition-cz-careteam-ems.html]]
class "cz-practitioner-core" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-practitioner-core.html]]
class "cz-practitionerrole-core" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-practitionerrole-core.html]]
class "cz-communication-ems" <<Profile>> [[StructureDefinition-cz-communication-ems.html]]
class "cz-relatedPerson-core" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition/cz-relatedPerson-core.html]]

"Dispatch data" <|. "cz-composition-ems"
"Dispatch data" <|. "cz-task-ems"
"Dispatch data" <|. "cz-location-ems"
"Dispatch data" <|. "cz-careteam-ems"
"Dispatch data" <|. "cz-practitioner-core"
"Dispatch data" <|. "cz-practitionerrole-core"
"Dispatch data" <|. "cz-communication-ems"
"Dispatch data" <|. "cz-vehicle-location-ems"
"Dispatch data" <|. "cz-relatedPerson-core"

"cz-composition-ems" -d[hidden]-> "cz-task-ems"
"cz-task-ems" -d[hidden]-> "cz-location-ems"
"cz-location-ems" -d[hidden]-> "cz-practitioner-core"
"cz-practitioner-core" -d[hidden]-> "cz-practitionerrole-core"
"cz-practitionerrole-core" -d[hidden]-> "cz-communication-ems"
"cz-communication-ems" -d[hidden]-> "cz-careteam-ems"
"cz-careteam-ems" -d[hidden]-> "cz-vehicle-location-ems"
"cz-vehicle-location-ems" -d[hidden]-> "cz-relatedPerson-core"

@enduml
