@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical model |
| <#TECHNOLOGY>  Profile |
endlegend

class "Dispatch timeline" <<LogicalModel>> [[StructureDefinition-DispatchTimelineCz.html]]
note top #EEEEAE [[ConceptMap-DispatchTimeline2FHIR-cz.html]]
Concept Map
endnote

class "cz-communication-ems" <<Profile>> [[StructureDefinition-cz-communication-ems.html]]
class "cz-encounter-mission-ems" <<Profile>> [[StructureDefinition-cz-encounter-mission-ems.html]]
class "cz-encounter-ems" <<Profile>> [[StructureDefinition-cz-encounter-ems.html]]

"Dispatch timeline" <|. "cz-encounter-ems"
"Dispatch timeline" <|. "cz-encounter-mission-ems"
"Dispatch timeline" <|. "cz-communication-ems"

"cz-encounter-ems" -d[hidden]-> "cz-encounter-mission-ems"
"cz-encounter-mission-ems" -d[hidden]-> "cz-communication-ems"

@enduml
