@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logický model |
| <#TECHNOLOGY>  Profil |
endlegend

class "Vizuální podoba dokumentu" <<LogicalModel>> [[StructureDefinition-LogPresentedFormCz.html]]
note top #EEEEAE [[ConceptMap-AttachmentEMS2FHIR-cz.html]]
Concept Mapa
endnote

class "cz-composition-ems" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-ems/StructureDefinition-cz-composition-ems.html]]

"Vizuální podoba dokumentu" <|. "cz-composition-ems"
"Vizuální podoba dokumentu" -d[hidden]-> "cz-composition-ems"

@enduml
