Logical: LogCzDispatchDataCz
Id: LogDispatchDataCz
Title: "A.2.1 - Údaje o výjezdu"
Description: """Záznam o výjezdu ZZS - Údaje o výjezdu"""
* identifikaceVyjezdu 1..1 Base "A.2.1.1 - Identifikace výjezdu" """Identifikace výjezdu"""
  * cisloVyjezdu 1..1 Identifier "A.2.1.1.1 - Číslo výjezdu" """Číslo výjezdu"""
  * dalsiIdentifikatorVyjezdu 0..* Identifier "A.2.1.1.2 - Další identifikátor výjezdu" """Další identifikátor výjezdu"""
* identifikaceVozidla 1..1 Base "A.2.1.2 - Identifikace vozidla" """Identifikace vozidla"""
  * registracniZnacka 1..1 Identifier "A.2.1.2.1 - Registrační značka" """Registrační značka vozidla - volací znak a registrační značka vozidla (ev. imatrikulace vrtulníku)"""
* identifikaceClenuVyjezdoveSkupiny 1..* Base "A.2.1.3 - Identifikace členů výjezdové skupiny" """Identifikace členů výjezdové skupiny"""
  * identifikatorClenaPosadky 1..1 Identifier "A.2.1.3.1 - Identifikátor člena posádky" """Identifikátor člena posádky"""
  * jmeno 1..1 string "A.2.1.3.2 - Jméno" """Jméno člena posádky"""
  * prijmeni 1..1 string "A.2.1.3.3 - Příjmení" """Příjmení člena posádky"""
  * role 1..1 CodeableConcept "A.2.1.3.4 - Role" """Role člena posádky"""
* identifikaceOperatoruZOS 1..1 Base "A.2.1.4 - Identifikace operátora ZOS" """Identifikace operátora ZOS"""
  * identifikatorOperatora 1..1 Identifier "A.2.1.4.1 - Identifikátor operátora" """Identifikátor operátora ZOS"""
  * jmeno 1..1 string "A.2.1.4.2 - Jméno" """Jméno operátora ZOS"""
  * prijmeni 1..1 string "A.2.1.4.3 - Příjmení" """Příjmení operátora ZOS"""
  * role 1..1 CodeableConcept "A.2.1.4.4 - Role" """Role operátora ZOS"""
* mistoZacatkuVyjezdu 1..1 Base "A.2.1.5 - Místo začátku výjezdu" """Místo odkud je výjezd realizován"""
  * adresa 1..1 Address "A.2.1.5.1 - Adresa" """Adresa nebo GPS souřadnice místa začátku výjezdu"""
* mistoUdalosti 1..1 Base "A.2.1.6 - Místo události" """Místo události zásahu"""
  * adresaGPS 1..1 Address "A.2.1.6.1 - Adresa - GPS" """GPS souřadnice místa události"""
  * adresa 0..1 Address "A.2.1.6.2 - Adresa" """Adresa místa události"""
* klasifikaceVyjezdu 1..1 Base "A.2.1.7 - Klasifikace výjezdu" """Klasifikace výjezdu"""
  * nalehavostVyjezdu 1..1 CodeableConcept "A.2.1.7.1 - Naléhavost výjezdu" """Naléhavost výjezdu (1 až 4)"""
  * klasifikaceVyzvy 1..1 CodeableConcept "A.2.1.7.2 - Klasifikace výzvy" """Klasifikace výzvy - předběžná informace o problému pacienta / důvod výjezdu"""
* kontaktVolajiciho 0..1 Base "A.2.1.8 - Kontakt volajícího" """Kontakt volajícího"""
  * telefon 1..1 ContactPoint "A.2.1.8.1 - Telefon" """Telefonní číslo volajícího"""