Logical: LogCzPatientHistoryCz
Id: LogCzPatientHistoryCz
Title: "A.2.3 - Anamnéza"
Description: """Zpráva o výjezdu - Anamnéza"""

* anamnezaOsobni 1..1 Base "A.2.3.1 - Osobní" """Osobní Anamnéza"""
  * zdravotniProblemy 1..* Base "A.2.3.1.1 - Historie zdravotních problémů" """Historie zdravotních problémů jiných, než je nynější onemocnění (které je součástí klinického shrnutí)."""
    * popisProblemu 1..1 string "A.2.3.1.1.1 - Popis problému" """Popis problému textem"""
    * kod 0..* Base "A.2.3.1.1.2 - Kód" """Formalizované vyjádření zdravotního problému kódem (klasifikace)."""
    * datumVzniku 1..1 dateTime "A.2.3.1.1.3 - Datum vzniku" """Datum či částečné datum případně věková kategorie vzniku onemocnění"""
    * datumVyreseni 0..1 dateTime "A.2.3.1.1.4 - Datum vyřešení či remise" """Datum či částečné datum případně věková kategorie vyřešení či ustoupení problému do remise. Problémy jejichž klinický stav je "aktivní" nemají tento údaj vyplněn."""
    * klinickyStav 0..1 CodeableConcept "A.2.3.1.1.5 - Klinický stav problému" """Klasifikace klinického stavu problému (aktivní, neaktivní)."""
    * okolnostiVyreseni 0..1 Base "A.2.3.1.1.6 - Okolnosti vyřešení" """Důvod, pro který se stav problému změnil na neaktivní..."""
    * zavaznost 0..1 CodeableConcept "A.2.3.1.1.7 - Závažnost" """Subjektivní hodnocení závažnosti problému klinikem."""
    * stadiumOnemocneni 0..* CodeableConcept "A.2.3.1.1.8 - Stadium onemocnění" """Stadium/grading problému dle zvolené škály textem a/nebo kódem."""
  * zp 1..* Base "A.2.3.1.2 - Historie zdravotních pomůcek a implantátů" """Historie implantátů a zdravotních pomůcek..."""
    * popis 1..1 CodeableConcept "A.2.3.1.2.1 - Popis zdravotnického prostředku" """Popis zdravotnického prostředku..."""
    * idZP 0..1 Identifier "A.2.3.1.2.2 - Identifikátor zdravotnického prostředku" """Normalizovaný identifikátor..."""
    * datumZavedeni 1..1 dateTime "A.2.3.1.2.3 - Datum zavedení" """Datum implantace..."""
    * datumOdstraneni 0..1 dateTime "A.2.3.1.2.4 - Datum odstranění" """Datum explantace..."""
    * duvod 0..* CodeableConcept "A.2.3.1.2.5 - Důvod použití" """Klinický důvod zavedení..."""
  * vyznamneVykony 0..* Base "A.2.3.1.3 - Významné výkony" """Významné výkony..."""
    * kodVykonu 0..1 CodeableConcept "A.2.3.1.3.1 - Kód výkonu" """Kód výkonu."""
    * popis 1..1 string "A.2.3.1.3.2 - Popis procedury" """Popis výkonu volným textem."""
    * lokalizace 0..1 CodeableConcept "A.2.3.1.3.3 - Lokalizace" """Anatomická lokace..."""
    * datum 0..1 dateTime "A.2.3.1.3.4 - Datum provedení" """Datum provedení výkonu..."""
    * duvod 0..1 CodeableConcept "A.2.3.1.3.5 - Důvod provedení" """Důvod provedení výkonu..."""
    * vysledek 0..1 CodeableConcept "A.2.3.1.3.6 - Výsledek" """Formalizované vyjádření výsledku výkonu..."""
    * pouzityZP 0..* Base "A.2.3.1.3.7 - Použitý zdravotnický prostředek" """Zdravotnický prostředek..."""
  * ockovani 0..* Base "A.2.3.1.4 - Očkování" """Historie očkování."""
    * puvodce 0..* CodeableConcept "A.2.3.1.4.1 - Onemocnění či původce" """Onemocnění či původce..."""
    * typVakciny 1..1 CodeableConcept "A.2.3.1.4.2 - Typ vakcíny" """Typ vakcíny vyjádřený kódem."""
    * ockovaciLatka 0..1 string "A.2.3.1.4.4 - Očkovací látka" """Registrovaný název vakcíny..."""
    * vyrobceVakciny 0..1 Base "A.2.3.1.4.5 - Držitel rozhodnutí" """Výrobce vakcíny..."""
    * poradoveCislo 0..1 integer "A.2.3.1.4.6 - Pořadové číslo dávky" """Pořadové číslo dávky."""
    * datumPodani 1..1 dateTime "A.2.3.1.4.7 - Datum podání dávky" """Přesné nebo přibližné datum podání."""
    * pristiVakcinace 0..1 dateTime "A.2.3.1.4.8 - Datum příští vakcinace" """Datum doporučeného přeočkování."""
  * epidemiologickaAnamneza 0..1 Base "A.2.3.1.5 - Epidemiologická anamnéza" """Cestovatelská anamnéza a infekční kontakty."""
    * infekcniKontakt 0..* Base "A.2.3.1.5.1 - Infekční kontakty" """Infekční kontakty pacienta"""
      * period 0..1 Period "A.2.3.1.5.1.1 - Období" """Období trvání infekčního kontaktu."""
      * infectiousAgent 0..* CodeableConcept "A.2.3.1.5.1.2 - Infekční onemocnění či agens" """In infekce..."""
      * proximity 0..1 CodeableConcept "A.2.3.1.5.1.3 - Vzdálenost" """Typ expozice či vzdálenost..."""
      * zeme 0..1 CodeableConcept "A.2.3.1.5.1.4 - Země" """Země, kde došlo ke kontaktu."""
      * komentar 0..1 string "A.2.3.1.5.1.5 - Komentář" """Poznámky..."""
    * cestovatelskaAnamneza 0..* Base "A.2.3.1.5.2 - Cestovatelská anamnéza" """Cestovatelská anamnéza."""
      * obdobi 0..1 Period "A.2.3.1.5.2.1 - Období" """Přesné či přibližné období pobytu."""
      * zeme 1..1 CodeableConcept "A.2.3.1.5.2.2 - Země" """Navštívená země."""
      * komentar 0..1 string "A.2.3.1.5.2.3 - Komentář" """Poznámky k pobytu."""
* rodinnaAnamneza 0..* Base "A.2.3.2 - Rodinná anamnéza" """Informace o závažných onemocněních u blízkých pokrevně příbuzných..."""
  * vztahKPacientovi 0..1 CodeableConcept "A.2.3.2.1 - Vztah k pacientovi" """Vztah osoby k pacientovi."""
  * datumNarozeni 0..1 dateTime "A.2.3.2.2 - Datum narození" """Přesné či přibližné datum narození."""
  * vekUmrti 0..1 Base "A.2.3.2.3 - Věk úmrtí" """Věk nebo datum úmrtí."""
   // vzdělání je zvlášť v A.2.3.3.2
  * zdravotniProblemy 0..* Base "A.2.3.2.5 - Zdravotní problémy" """Zdravotní problémy, jimiž osoba trpí či trpěla."""
  * duvodUmrti 0..1 CodeableConcept "A.2.3.2.6 - Důvod úmrtí" """Příčina úmrtí."""
* socialniAnamneza 0..1 Base "A.2.3.3 - Sociální anamnéza" """Sociální anamnéza"""
  * spolecenskeUplatneni 0..1 Base "A.2.3.3.1 - Společenské uplatnění" """Společenské zapojení..."""
    * pracovniZapojeni 0..1 string "A.2.3.3.1.1 - Pracovní zapojení" """Pracovním zapojením je..."""
    * konicky 0..1 string "A.2.3.3.1.2 - Koníčky" """Záliby..."""
    * socialniSit 0..1 string "A.2.3.3.1.3 - Sociální síť" """Popis sociální sítě..."""
  * vzdelani 0..1 Base "A.2.3.3.2 - Vzdělání" """Vzdělání"""
    * uroven 0..1 CodeableConcept "A.2.3.3.2.1 - Dosažený stupeň vzdělání" """Stupeň dosaženého vzdělání"""
    * komentar 0..1 string "A.2.3.3.2.2 - Komentář" """Upřesnění..."""
  * bydleni 0..1 Base "A.2.3.3.3 - Bydlení" """Způsob bydlení..."""
    * zpusobBydleni 0..1 CodeableConcept "A.2.3.3.3.1 - Způsob bydlení" """Druh bydlení..."""
    * prizpusobeni 0..* CodeableConcept "A.2.3.3.3.2 - Přizpůsobení" """Úpravy domácnosti..."""
    * bariery 0..* CodeableConcept "A.2.3.3.3.3 - Bariéry" """Podmínky bezbariérovosti."""
  * rodinnaSituace 0..1 Base "A.2.3.3.4 - Rodinná situace" """Podrobnosti rodinné situace."""
    * komentar 0..1 string "A.2.3.3.4.1 - Komentář" """Komentář k rodinné situaci."""
    * slozeniRodiny 0..1 CodeableConcept "A.2.3.3.4.2 - Složení rodiny" """Složení rodiny."""
    * rodinnyStav 0..1 CodeableConcept "A.2.3.3.4.3 - Rodinný stav" """Rodinný stav."""
    * pocetDeti 0..1 integer "A.2.3.3.4.4 - Počet dětí" """Celkový počet dětí..."""
    * pocetDetiDoma 0..1 integer "A.2.3.3.4.5 - Počet dětí ve společné domácnosti" """Počet dětí žijících doma."""
    * podrobnostiODiteti 0..* Base "A.2.3.3.4.6 - Podrobnosti o dítěti" """Pro každé dítě: datum narození..."""
    * pecujeO 0..* Base "A.2.3.3.4.7 - Pečuje o" """Činnosti, které pacient vykonává při péči o závislého člena rodiny."""
* abusus 0..1 Base "A.2.3.4 - Abusus" """Informace o pravidelném kouření..."""
  * alkohol 0..* Base "A.2.3.4.1 - Alkohol" """Konzumace alkoholu."""
    * stav 0..1 CodeableConcept "A.2.3.4.1.1 - Stav" """Aktuální stav."""
    * mnozstvi 0..* CodeableConcept "A.2.3.4.1.2 - Období a množství" """Období a množství."""
    * komentar 0..1 string "A.2.3.4.1.3 - Komentář" """Komentář volným textem."""
  * koureni 0..* Base "A.2.3.4.2 - Kouření" """Kouření."""
    * stav 0..1 CodeableConcept "A.2.3.4.2.1 - Stav" """Stav kouření kódem."""
    * mnozstvi 0..* Base "A.2.3.4.2.2 - Období a průměrné množství." """Období a množství."""
    * komentar 0..1 string "A.2.3.4.2.3 - Komentář" """Komentář volným textem."""
  * drogy 0..* Base "A.2.3.4.3 - Drogy" """Drogová závislost."""
    * stav 0..1 CodeableConcept "A.2.3.4.3.1 - Stav" """Aktuální stav drogové závislosti."""
    * mnozstvi 0..1 Base "A.2.3.4.3.2 - Období a množství" """Období a množství/kvantifikace."""
    * typLatky 0..1 CodeableConcept "A.2.3.4.3.3 - Typ látky" """Typ užívané látky."""
    * zpusobPodani 0..* CodeableConcept "A.2.3.4.3.4 - Způsob podávání" """Způsob administrace látky."""
    * komentar 0..1 string "A.2.3.4.3.5 - Komentář" """Komentář volným textem."""
